/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#713700",
        "surface-container-highest": "#e7e0ed",
        "surface-bright": "#fef7ff",
        "surface-dim": "#ded7e4",
        "outline": "#7b7486",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#8c0053",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#d0bcff",
        "secondary-fixed": "#ffd9e5",
        "tertiary": "#6e3500",
        "surface-tint": "#6d3bd6",
        "secondary": "#b4136e",
        "on-primary-fixed": "#23005c",
        "primary": "#5312bc",
        "inverse-primary": "#d0bcff",
        "on-background": "#1d1a23",
        "on-surface": "#1d1a23",
        "on-surface-variant": "#494454",
        "surface-container": "#f3ebf8",
        "on-primary": "#ffffff",
        "surface-variant": "#e7e0ed",
        "secondary-fixed-dim": "#ffb0cd",
        "background": "#fef7ff",
        "primary-fixed": "#e9ddff",
        "tertiary-fixed": "#ffdcc6",
        "inverse-surface": "#322f39",
        "secondary-container": "#fd56a7",
        "on-error-container": "#93000a",
        "outline-variant": "#cbc3d7",
        "on-tertiary": "#ffffff",
        "primary-container": "#6b38d4",
        "on-secondary-fixed": "#3e0022",
        "tertiary-container": "#914800",
        "on-error": "#ffffff",
        "surface-container-high": "#ede5f3",
        "on-primary-container": "#ddcdff",
        "surface-container-low": "#f8f1fe",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffcaa7",
        "surface": "#fef7ff",
        "tertiary-fixed-dim": "#ffb785",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#5517be",
        "on-secondary-container": "#600037",
        "inverse-on-surface": "#f5eefb",
        "on-tertiary-fixed": "#301400"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "3xl": "32px"
      },
      spacing: {
        "base": "8px",
        "lg": "40px",
        "margin-desktop": "32px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "gutter": "20px",
        "xl": "64px",
        "margin-mobile": "16px",
        "stack-lg": "48px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "container-padding": "24px",
        "container-padding-desktop": "32px",
        "container-padding-mobile": "16px"
      },
      fontFamily: {
        "headline-md": ["Space Grotesk"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
